baseURL = "https://alx.github.io/basecamp/"
languageCode = "en-us"
title = "BaseCamp AI"

[params]
  description = "Sovereign AI. Local. Secure."
  tagline = "From Paper to Private AI"

[outputs]
  home = ["HTML"]
  page = ["HTML"]
